version: "3.9"
services:
  custom-cnn-fpga:
    image: 2441139/cotton-plant-disease-detection:latest
    pull_policy: if_not_present
    container_name: custom_cnn_fpga
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    volumes:
      - ./models:/workspace/models
      - ./images:/workspace/images
      - ./results:/workspace/results
    ports:
      - "7860:7860"
      - "5000:5000"
    command: ["sleep", "infinity"]
    restart: unless-stopped

networks:
  default:
    name: custom_cnn_fpga_default